language: node_js
node_js: node
deploy:
  provider: heroku
  api_key: 269105c8-1619-4341-b382-40cad8a59ae5
    secure: cu3lOXHo2e6ObheCLxCq+6SwYeCipApRbGdrKadVDMRAG6c6llXB6ihZOCE1wi2tg/W4WTaPgKtCfIC2ez7fdqyLfM3O2DbJ4JkHxsBSUtLzIQOXzhZslo4MrP2Yr4vspiwqytvACuH0G2mokDydd0nzc77+0oR1RenwU7DULbK0XGyt3XkvOdvGfguNXR8dOFCgA2SMuvd7gQUPMkdvhrwr7fZfCuz6eoNVufcDzclucdaLll6qH7ZHdPGvAnYF94ErHyRXt0Bpo604jJxKMTiuEHvdeZ6Ru86E4IArAcde0qiNtOkuVOOur3q4sAQsRAjGZ4KjUMy5m7yyPk/xwBkrhuTDUQ8soT8RFQ3gN2XpP5DA+2Gpu3IwsT3QwT2mcDNZ5pHJNhByjsIDVZhQoAWGFwdJNgjzwrRS0O/SnXHgslB4cSRBN48JdMuWP8GrMUCVbrF4PwD5XSBGhOQEuO2Gty0guW6XGve6l0zaqlEiLMeMvYk6b9dSCsyJInZzf34KzTXJnA1MtN6lk2Cn25zyfciRMHKnF64qR8mNjjFwTZ2LX9/hLIoJWBJw8aLn/MzMYbWq9XagXk2ylYgyErCy7yj/ktqGy9PgTv0DACiFneVAZULtl+Ld87BO84K/3XQnH0ooHwbkZx6oYEGWHVetx35v0kOyVK7SRQh5JsI=
  app: mighty-tor-64667
  on:
    repo: sans-amanda/Thinkful-Node-Capstone
