language: node_js
node_js: node
deploy:
  provider: heroku
  edge: true
  api_key:
    secure: c1043e10-bf7a-4c2d-a960-fe902f5881b7
  app: shrouded-reaches-59652
  on:
    repo: sans-amanda/Thinkful-Node-Capstone
